name: Tabak Vladimir
job: QA Engineer
level: junior
email: vova-tabak@mail.ru
description: |
  Я наконец начал изучение в IT. Решил поменять свою жизнь и заниматься тем, чем хочу.
skills:
  - Функциональное тестирование
  - Написание багрепортов
  - Linux, MacOS, Windows.
  - Слепая печать
  - Английский язык C1
  - Работаю с DevTools, Postman, Git
  - обладаю навыками создания SQL-запросов.
