---
  Functional:
    - Пользователь должен иметь возможность искать товары по ключевому слову или категории
    - Пользователь должен иметь возможность фильтровать товары
    - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
    - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
    - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее
    - Пользователь должен иметь возможность добавлять товар в корзину и продолжать выбирать товары в каталоге
    - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге
    - На странице корзины пользователь может оформить заказ с переходом на страницу оплаты
  non-functional:
    - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
    - Сайт должен быть безопасным и защищать данные пользователя
    - Сайт должен иметь мобильную версию
    - Сайт нужно протестировать на совместимость с последними версиями браузеров
    - Важно, чтобы сайт мог обрабатывать большое количество трафика
    - Сайт должен быть доступен на различных устройствах
    - Пользователь должен иметь возможность переключить язык интерфейса
    - Сайт должен иметь локализацию (перевод) на русский и английский языки
    - Сайт должен быть SPA-приложение
    - Корзина пользователя должна храниться в сессии браузера
  implicit:
    - Сайт должен соответствовать всем применимым законам и нормативным актам
    - При переключении языка интерфейса во вкладке "Язык" отображается флаг, соответствующий выбранному языку. 
    - Данные пользователя  должны сохраняться при переходе между страницами и в случае кратковременного отключения интернета.
    - Сайт должен быть доступен для людей с ограниченными возможностями
    - При удалении товара из корзины, обычно отображается подтверждающее уведомление или баннер, чтобы уведомить пользователя о успешном удалении товара и избежать случайного удаления
    - На сайте должна быть размещена информация о политике конфиденциальности, условиях использования, политике возврата, собственнике интернет-магазина ( наименоваие, ОГРН, юридический и фактический адреса, электронная почта, номер телефона для связи)
    - Фотографии и описания товаров должны быть качественными и информативными
    - Платежные операции должны быть защищены надежными механизмами шифрования
    - Пользователь не может оформить заказ на товар, которого нет в наличии
    - Все названия категорий и производителей в фильтре должны отображаться в алфавитном порядке
